package javaee.spring.test.pojo.system;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.ADDRESS_NAME
     *
     * @mbggenerated
     */
    private String addressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.OPTLOCK
     *
     * @mbggenerated
     */
    private Integer optlock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ID
     *
     * @return the value of address.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ID
     *
     * @param id the value for address.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.ADDRESS_NAME
     *
     * @return the value of address.ADDRESS_NAME
     *
     * @mbggenerated
     */
    public String getAddressName() {
        return addressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.ADDRESS_NAME
     *
     * @param addressName the value for address.ADDRESS_NAME
     *
     * @mbggenerated
     */
    public void setAddressName(String addressName) {
        this.addressName = addressName == null ? null : addressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.OPTLOCK
     *
     * @return the value of address.OPTLOCK
     *
     * @mbggenerated
     */
    public Integer getOptlock() {
        return optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.OPTLOCK
     *
     * @param optlock the value for address.OPTLOCK
     *
     * @mbggenerated
     */
    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }
}