package javaee.spring.test.pojo.system;

public class People {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.PEOPLE_NAME
     *
     * @mbggenerated
     */
    private String peopleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column people.OPTLOCK
     *
     * @mbggenerated
     */
    private Integer optlock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.ID
     *
     * @return the value of people.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.ID
     *
     * @param id the value for people.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.PEOPLE_NAME
     *
     * @return the value of people.PEOPLE_NAME
     *
     * @mbggenerated
     */
    public String getPeopleName() {
        return peopleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.PEOPLE_NAME
     *
     * @param peopleName the value for people.PEOPLE_NAME
     *
     * @mbggenerated
     */
    public void setPeopleName(String peopleName) {
        this.peopleName = peopleName == null ? null : peopleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column people.OPTLOCK
     *
     * @return the value of people.OPTLOCK
     *
     * @mbggenerated
     */
    public Integer getOptlock() {
        return optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column people.OPTLOCK
     *
     * @param optlock the value for people.OPTLOCK
     *
     * @mbggenerated
     */
    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }
}