package javaee.spring.test.pojo.system;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.STUDENT_NAME
     *
     * @mbggenerated
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.OPTLOCK
     *
     * @mbggenerated
     */
    private Integer optlock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param id the value for student.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.STUDENT_NAME
     *
     * @return the value of student.STUDENT_NAME
     *
     * @mbggenerated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.STUDENT_NAME
     *
     * @param studentName the value for student.STUDENT_NAME
     *
     * @mbggenerated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.OPTLOCK
     *
     * @return the value of student.OPTLOCK
     *
     * @mbggenerated
     */
    public Integer getOptlock() {
        return optlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.OPTLOCK
     *
     * @param optlock the value for student.OPTLOCK
     *
     * @mbggenerated
     */
    public void setOptlock(Integer optlock) {
        this.optlock = optlock;
    }
}