package javaee.spring.test.pojo.system;

import java.util.Date;

public class TmSecPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_CODE
     *
     * @mbggenerated
     */
    private String resCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_NAME
     *
     * @mbggenerated
     */
    private String resName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_NAME_CN
     *
     * @mbggenerated
     */
    private String resNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_SEQUENCE
     *
     * @mbggenerated
     */
    private Integer resSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_TYPE
     *
     * @mbggenerated
     */
    private String resType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_PARENT
     *
     * @mbggenerated
     */
    private String resParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.RES_CONTENT
     *
     * @mbggenerated
     */
    private String resContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.CREATE_USER
     *
     * @mbggenerated
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.LAST_MODIFIED_USER
     *
     * @mbggenerated
     */
    private Long lastModifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_sec_permission.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.ID
     *
     * @return the value of tm_sec_permission.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.ID
     *
     * @param id the value for tm_sec_permission.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_CODE
     *
     * @return the value of tm_sec_permission.RES_CODE
     *
     * @mbggenerated
     */
    public String getResCode() {
        return resCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_CODE
     *
     * @param resCode the value for tm_sec_permission.RES_CODE
     *
     * @mbggenerated
     */
    public void setResCode(String resCode) {
        this.resCode = resCode == null ? null : resCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_NAME
     *
     * @return the value of tm_sec_permission.RES_NAME
     *
     * @mbggenerated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_NAME
     *
     * @param resName the value for tm_sec_permission.RES_NAME
     *
     * @mbggenerated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_NAME_CN
     *
     * @return the value of tm_sec_permission.RES_NAME_CN
     *
     * @mbggenerated
     */
    public String getResNameCn() {
        return resNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_NAME_CN
     *
     * @param resNameCn the value for tm_sec_permission.RES_NAME_CN
     *
     * @mbggenerated
     */
    public void setResNameCn(String resNameCn) {
        this.resNameCn = resNameCn == null ? null : resNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_SEQUENCE
     *
     * @return the value of tm_sec_permission.RES_SEQUENCE
     *
     * @mbggenerated
     */
    public Integer getResSequence() {
        return resSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_SEQUENCE
     *
     * @param resSequence the value for tm_sec_permission.RES_SEQUENCE
     *
     * @mbggenerated
     */
    public void setResSequence(Integer resSequence) {
        this.resSequence = resSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_TYPE
     *
     * @return the value of tm_sec_permission.RES_TYPE
     *
     * @mbggenerated
     */
    public String getResType() {
        return resType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_TYPE
     *
     * @param resType the value for tm_sec_permission.RES_TYPE
     *
     * @mbggenerated
     */
    public void setResType(String resType) {
        this.resType = resType == null ? null : resType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_PARENT
     *
     * @return the value of tm_sec_permission.RES_PARENT
     *
     * @mbggenerated
     */
    public String getResParent() {
        return resParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_PARENT
     *
     * @param resParent the value for tm_sec_permission.RES_PARENT
     *
     * @mbggenerated
     */
    public void setResParent(String resParent) {
        this.resParent = resParent == null ? null : resParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.REMARK
     *
     * @return the value of tm_sec_permission.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.REMARK
     *
     * @param remark the value for tm_sec_permission.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.STATUS
     *
     * @return the value of tm_sec_permission.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.STATUS
     *
     * @param status the value for tm_sec_permission.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.RES_CONTENT
     *
     * @return the value of tm_sec_permission.RES_CONTENT
     *
     * @mbggenerated
     */
    public String getResContent() {
        return resContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.RES_CONTENT
     *
     * @param resContent the value for tm_sec_permission.RES_CONTENT
     *
     * @mbggenerated
     */
    public void setResContent(String resContent) {
        this.resContent = resContent == null ? null : resContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.CREATE_USER
     *
     * @return the value of tm_sec_permission.CREATE_USER
     *
     * @mbggenerated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.CREATE_USER
     *
     * @param createUser the value for tm_sec_permission.CREATE_USER
     *
     * @mbggenerated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.CREATE_TIME
     *
     * @return the value of tm_sec_permission.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.CREATE_TIME
     *
     * @param createTime the value for tm_sec_permission.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.LAST_MODIFIED_USER
     *
     * @return the value of tm_sec_permission.LAST_MODIFIED_USER
     *
     * @mbggenerated
     */
    public Long getLastModifiedUser() {
        return lastModifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.LAST_MODIFIED_USER
     *
     * @param lastModifiedUser the value for tm_sec_permission.LAST_MODIFIED_USER
     *
     * @mbggenerated
     */
    public void setLastModifiedUser(Long lastModifiedUser) {
        this.lastModifiedUser = lastModifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_sec_permission.LAST_MODIFIED_TIME
     *
     * @return the value of tm_sec_permission.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_sec_permission.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for tm_sec_permission.LAST_MODIFIED_TIME
     *
     * @mbggenerated
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }
}