package javaee.spring.test.mybatis.system;

import javaee.spring.test.pojo.system.TmSecUserRole;

public interface TmSecUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_user_role
     *
     * @mbggenerated
     */
    int insert(TmSecUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_user_role
     *
     * @mbggenerated
     */
    int insertSelective(TmSecUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_user_role
     *
     * @mbggenerated
     */
    TmSecUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmSecUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmSecUserRole record);
}