package javaee.spring.test.mybatis.system;

import javaee.spring.test.pojo.system.TmSecPermission;

public interface TmSecPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_permission
     *
     * @mbggenerated
     */
    int insert(TmSecPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_permission
     *
     * @mbggenerated
     */
    int insertSelective(TmSecPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_permission
     *
     * @mbggenerated
     */
    TmSecPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmSecPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmSecPermission record);
}