package javaee.spring.test.mybatis.system;

import javaee.spring.test.pojo.system.TmSecRolePermission;

public interface TmSecRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role_permission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role_permission
     *
     * @mbggenerated
     */
    int insert(TmSecRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role_permission
     *
     * @mbggenerated
     */
    int insertSelective(TmSecRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role_permission
     *
     * @mbggenerated
     */
    TmSecRolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmSecRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role_permission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmSecRolePermission record);
}