package javaee.spring.test.mybatis.system;

import javaee.spring.test.pojo.system.TmSecRole;

public interface TmSecRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role
     *
     * @mbggenerated
     */
    int insert(TmSecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role
     *
     * @mbggenerated
     */
    int insertSelective(TmSecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role
     *
     * @mbggenerated
     */
    TmSecRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmSecRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_sec_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmSecRole record);
}